# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.runs/synth_1/design_2_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.cache/wt [current_project]
set_property parent.project_path C:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/giova/AppData/Roaming/Xilinx/Vivado/2021.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib C:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/hdl/design_2_wrapper.vhd
add_files C:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_microblaze_0_3/design_2_microblaze_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_microblaze_0_3/design_2_microblaze_0_3_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_microblaze_0_3/design_2_microblaze_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_dlmb_v10_3/design_2_dlmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_ilmb_v10_3/design_2_ilmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_dlmb_bram_if_cntlr_3/design_2_dlmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_ilmb_bram_if_cntlr_3/design_2_ilmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_lmb_bram_3/design_2_lmb_bram_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_100M_1/design_2_rst_clk_wiz_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_100M_1/design_2_rst_clk_wiz_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_100M_1/design_2_rst_clk_wiz_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_2/design_2_floating_point_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_1_0/design_2_floating_point_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_0/design_2_floating_point_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_1/design_2_floating_point_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_3/design_2_floating_point_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_1_1/design_2_floating_point_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_4_0/design_2_floating_point_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_0/design_2_axis_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_0/design_2_axis_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_2_0/design_2_floating_point_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_3_0/design_2_floating_point_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_4/design_2_floating_point_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_1_2/design_2_floating_point_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_4_3/design_2_floating_point_4_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_5_0/design_2_floating_point_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_6_0/design_2_floating_point_6_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_1/design_2_axis_register_slice_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_1/design_2_axis_register_slice_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_2_2/design_2_floating_point_2_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_3_2/design_2_floating_point_3_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_6/design_2_floating_point_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_1_4/design_2_floating_point_1_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_4_5/design_2_floating_point_4_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_5_2/design_2_floating_point_5_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_6_2/design_2_floating_point_6_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_3/design_2_axis_register_slice_0_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_3/design_2_axis_register_slice_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_2_3/design_2_floating_point_2_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_3_3/design_2_floating_point_3_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_7/design_2_floating_point_0_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_1_5/design_2_floating_point_1_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_4_6/design_2_floating_point_4_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_5_3/design_2_floating_point_5_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_6_3/design_2_floating_point_6_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_4/design_2_axis_register_slice_0_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_4/design_2_axis_register_slice_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_2_4/design_2_floating_point_2_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_3_4/design_2_floating_point_3_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_8/design_2_floating_point_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_1_6/design_2_floating_point_1_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_4_7/design_2_floating_point_4_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_5_4/design_2_floating_point_5_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_6_4/design_2_floating_point_6_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_5/design_2_axis_register_slice_0_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_5/design_2_axis_register_slice_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_2_5/design_2_floating_point_2_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_3_5/design_2_floating_point_3_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_9/design_2_floating_point_0_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_1_7/design_2_floating_point_1_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_4_8/design_2_floating_point_4_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_5_5/design_2_floating_point_5_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_6_5/design_2_floating_point_6_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_6/design_2_axis_register_slice_0_6_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_6/design_2_axis_register_slice_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_2_6/design_2_floating_point_2_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_3_6/design_2_floating_point_3_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_10/design_2_floating_point_0_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_1_8/design_2_floating_point_1_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_4_9/design_2_floating_point_4_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_5_6/design_2_floating_point_5_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_6_6/design_2_floating_point_6_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_7/design_2_axis_register_slice_0_7_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_7/design_2_axis_register_slice_0_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_xbar_2/design_2_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_gpio_0_5/design_2_axi_gpio_0_5_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_gpio_0_5/design_2_axi_gpio_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_gpio_0_5/design_2_axi_gpio_0_5.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_gpio_0_6/design_2_axi_gpio_0_6_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_gpio_0_6/design_2_axi_gpio_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_gpio_0_6/design_2_axi_gpio_0_6.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_input_0_0/design_2_input_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_input_0_0/design_2_input_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_input_0_0/design_2_input_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_input_0_1/design_2_input_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_input_0_1/design_2_input_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_input_0_1/design_2_input_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_input_2_0/design_2_input_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_input_2_0/design_2_input_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_input_2_0/design_2_input_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_fifo_mm_s_0_0/design_2_axi_fifo_mm_s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_fifo_mm_s_0_1/design_2_axi_fifo_mm_s_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_fifo_mm_s_0_2/design_2_axi_fifo_mm_s_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axi_fifo_mm_s_0_3/design_2_axi_fifo_mm_s_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_2_1/design_2_floating_point_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_3_1/design_2_floating_point_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_0_5/design_2_floating_point_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_1_3/design_2_floating_point_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_4_4/design_2_floating_point_4_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_5_1/design_2_floating_point_5_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_floating_point_6_1/design_2_floating_point_6_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_2/design_2_axis_register_slice_0_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_2/design_2_axis_register_slice_0_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_1/bd_0/ip/ip_0/bd_c78d_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_1/bd_0/bd_c78d_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_1/design_2_system_ila_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/design_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_microblaze_0_3/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files C:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.srcs/constrs_1/new/constraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.srcs/utils_1/imports/synth_1/design_2_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_2_wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_2_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_2_wrapper_utilization_synth.rpt -pb design_2_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
