# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_1 || ORIG_REF_NAME==design_2_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_3/design_2_microblaze_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_3 || ORIG_REF_NAME==design_2_microblaze_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_v10_3/design_2_dlmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_v10_3 || ORIG_REF_NAME==design_2_dlmb_v10_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_v10_3/design_2_ilmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_v10_3 || ORIG_REF_NAME==design_2_ilmb_v10_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_bram_if_cntlr_3/design_2_dlmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==design_2_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_bram_if_cntlr_3/design_2_ilmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==design_2_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_lmb_bram_3/design_2_lmb_bram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_lmb_bram_3 || ORIG_REF_NAME==design_2_lmb_bram_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_mdm_1_0 || ORIG_REF_NAME==design_2_mdm_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_clk_wiz_0_100M_1/design_2_rst_clk_wiz_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_0_100M_1 || ORIG_REF_NAME==design_2_rst_clk_wiz_0_100M_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_2/design_2_floating_point_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_2 || ORIG_REF_NAME==design_2_floating_point_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_1_0/design_2_floating_point_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_1_0 || ORIG_REF_NAME==design_2_floating_point_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_0/design_2_floating_point_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_0 || ORIG_REF_NAME==design_2_floating_point_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_1/design_2_floating_point_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_1 || ORIG_REF_NAME==design_2_floating_point_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_3/design_2_floating_point_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_3 || ORIG_REF_NAME==design_2_floating_point_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_1_1/design_2_floating_point_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_1_1 || ORIG_REF_NAME==design_2_floating_point_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_4_0/design_2_floating_point_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_4_0 || ORIG_REF_NAME==design_2_floating_point_4_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_0/design_2_Weight_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_0 || ORIG_REF_NAME==design_2_Weight_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_1/design_2_Weight_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_1 || ORIG_REF_NAME==design_2_Weight_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_2/design_2_Weight_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_2 || ORIG_REF_NAME==design_2_Weight_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_register_slice_0_0/design_2_axis_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_register_slice_0_0 || ORIG_REF_NAME==design_2_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_3/design_2_Weight_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_3 || ORIG_REF_NAME==design_2_Weight_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_0_0/design_2_Tvalid_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_0_0 || ORIG_REF_NAME==design_2_Tvalid_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_1_0/design_2_Tvalid_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_1_0 || ORIG_REF_NAME==design_2_Tvalid_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_1_1/design_2_Tvalid_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_1_1 || ORIG_REF_NAME==design_2_Tvalid_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ReLu_0_0/design_2_ReLu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ReLu_0_0 || ORIG_REF_NAME==design_2_ReLu_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_2_0/design_2_floating_point_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_2_0 || ORIG_REF_NAME==design_2_floating_point_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_3_0/design_2_floating_point_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_3_0 || ORIG_REF_NAME==design_2_floating_point_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_4/design_2_floating_point_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_4 || ORIG_REF_NAME==design_2_floating_point_0_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_1_2/design_2_floating_point_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_1_2 || ORIG_REF_NAME==design_2_floating_point_1_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_4_3/design_2_floating_point_4_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_4_3 || ORIG_REF_NAME==design_2_floating_point_4_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_5_0/design_2_floating_point_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_5_0 || ORIG_REF_NAME==design_2_floating_point_5_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_6_0/design_2_floating_point_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_6_0 || ORIG_REF_NAME==design_2_floating_point_6_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_4/design_2_Weight_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_4 || ORIG_REF_NAME==design_2_Weight_0_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_1_0/design_2_Weight_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_1_0 || ORIG_REF_NAME==design_2_Weight_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_2_0/design_2_Weight_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_2_0 || ORIG_REF_NAME==design_2_Weight_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_3_0/design_2_Weight_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_3_0 || ORIG_REF_NAME==design_2_Weight_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_register_slice_0_1/design_2_axis_register_slice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_register_slice_0_1 || ORIG_REF_NAME==design_2_axis_register_slice_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_0_1/design_2_Tvalid_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_0_1 || ORIG_REF_NAME==design_2_Tvalid_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_1_2/design_2_Tvalid_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_1_2 || ORIG_REF_NAME==design_2_Tvalid_1_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_2_0/design_2_Tvalid_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_2_0 || ORIG_REF_NAME==design_2_Tvalid_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_3_0/design_2_Tvalid_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_3_0 || ORIG_REF_NAME==design_2_Tvalid_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ReLu_0_1/design_2_ReLu_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ReLu_0_1 || ORIG_REF_NAME==design_2_ReLu_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_2_2/design_2_floating_point_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_2_2 || ORIG_REF_NAME==design_2_floating_point_2_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_3_2/design_2_floating_point_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_3_2 || ORIG_REF_NAME==design_2_floating_point_3_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_6/design_2_floating_point_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_6 || ORIG_REF_NAME==design_2_floating_point_0_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_1_4/design_2_floating_point_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_1_4 || ORIG_REF_NAME==design_2_floating_point_1_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_4_5/design_2_floating_point_4_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_4_5 || ORIG_REF_NAME==design_2_floating_point_4_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_5_2/design_2_floating_point_5_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_5_2 || ORIG_REF_NAME==design_2_floating_point_5_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_6_2/design_2_floating_point_6_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_6_2 || ORIG_REF_NAME==design_2_floating_point_6_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_6/design_2_Weight_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_6 || ORIG_REF_NAME==design_2_Weight_0_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_1_2/design_2_Weight_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_1_2 || ORIG_REF_NAME==design_2_Weight_1_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_2_2/design_2_Weight_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_2_2 || ORIG_REF_NAME==design_2_Weight_2_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_3_2/design_2_Weight_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_3_2 || ORIG_REF_NAME==design_2_Weight_3_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_register_slice_0_3/design_2_axis_register_slice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_register_slice_0_3 || ORIG_REF_NAME==design_2_axis_register_slice_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_0_3/design_2_Tvalid_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_0_3 || ORIG_REF_NAME==design_2_Tvalid_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_1_4/design_2_Tvalid_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_1_4 || ORIG_REF_NAME==design_2_Tvalid_1_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_2_2/design_2_Tvalid_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_2_2 || ORIG_REF_NAME==design_2_Tvalid_2_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_3_2/design_2_Tvalid_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_3_2 || ORIG_REF_NAME==design_2_Tvalid_3_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ReLu_0_3/design_2_ReLu_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ReLu_0_3 || ORIG_REF_NAME==design_2_ReLu_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_2_3/design_2_floating_point_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_2_3 || ORIG_REF_NAME==design_2_floating_point_2_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_3_3/design_2_floating_point_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_3_3 || ORIG_REF_NAME==design_2_floating_point_3_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_7/design_2_floating_point_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_7 || ORIG_REF_NAME==design_2_floating_point_0_7} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_1_5/design_2_floating_point_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_1_5 || ORIG_REF_NAME==design_2_floating_point_1_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_4_6/design_2_floating_point_4_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_4_6 || ORIG_REF_NAME==design_2_floating_point_4_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_5_3/design_2_floating_point_5_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_5_3 || ORIG_REF_NAME==design_2_floating_point_5_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_6_3/design_2_floating_point_6_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_6_3 || ORIG_REF_NAME==design_2_floating_point_6_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_7/design_2_Weight_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_7 || ORIG_REF_NAME==design_2_Weight_0_7} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_1_3/design_2_Weight_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_1_3 || ORIG_REF_NAME==design_2_Weight_1_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_2_3/design_2_Weight_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_2_3 || ORIG_REF_NAME==design_2_Weight_2_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_3_3/design_2_Weight_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_3_3 || ORIG_REF_NAME==design_2_Weight_3_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_register_slice_0_4/design_2_axis_register_slice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_register_slice_0_4 || ORIG_REF_NAME==design_2_axis_register_slice_0_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_0_4/design_2_Tvalid_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_0_4 || ORIG_REF_NAME==design_2_Tvalid_0_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_1_5/design_2_Tvalid_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_1_5 || ORIG_REF_NAME==design_2_Tvalid_1_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_2_3/design_2_Tvalid_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_2_3 || ORIG_REF_NAME==design_2_Tvalid_2_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_3_3/design_2_Tvalid_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_3_3 || ORIG_REF_NAME==design_2_Tvalid_3_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ReLu_0_4/design_2_ReLu_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ReLu_0_4 || ORIG_REF_NAME==design_2_ReLu_0_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_2_4/design_2_floating_point_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_2_4 || ORIG_REF_NAME==design_2_floating_point_2_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_3_4/design_2_floating_point_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_3_4 || ORIG_REF_NAME==design_2_floating_point_3_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_8/design_2_floating_point_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_8 || ORIG_REF_NAME==design_2_floating_point_0_8} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_1_6/design_2_floating_point_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_1_6 || ORIG_REF_NAME==design_2_floating_point_1_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_4_7/design_2_floating_point_4_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_4_7 || ORIG_REF_NAME==design_2_floating_point_4_7} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_5_4/design_2_floating_point_5_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_5_4 || ORIG_REF_NAME==design_2_floating_point_5_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_6_4/design_2_floating_point_6_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_6_4 || ORIG_REF_NAME==design_2_floating_point_6_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_8/design_2_Weight_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_8 || ORIG_REF_NAME==design_2_Weight_0_8} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_1_4/design_2_Weight_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_1_4 || ORIG_REF_NAME==design_2_Weight_1_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_2_4/design_2_Weight_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_2_4 || ORIG_REF_NAME==design_2_Weight_2_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_3_4/design_2_Weight_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_3_4 || ORIG_REF_NAME==design_2_Weight_3_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_register_slice_0_5/design_2_axis_register_slice_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_register_slice_0_5 || ORIG_REF_NAME==design_2_axis_register_slice_0_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_0_5/design_2_Tvalid_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_0_5 || ORIG_REF_NAME==design_2_Tvalid_0_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_1_6/design_2_Tvalid_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_1_6 || ORIG_REF_NAME==design_2_Tvalid_1_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_2_4/design_2_Tvalid_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_2_4 || ORIG_REF_NAME==design_2_Tvalid_2_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_3_4/design_2_Tvalid_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_3_4 || ORIG_REF_NAME==design_2_Tvalid_3_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ReLu_0_5/design_2_ReLu_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ReLu_0_5 || ORIG_REF_NAME==design_2_ReLu_0_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_2_5/design_2_floating_point_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_2_5 || ORIG_REF_NAME==design_2_floating_point_2_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_3_5/design_2_floating_point_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_3_5 || ORIG_REF_NAME==design_2_floating_point_3_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_9/design_2_floating_point_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_9 || ORIG_REF_NAME==design_2_floating_point_0_9} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_1_7/design_2_floating_point_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_1_7 || ORIG_REF_NAME==design_2_floating_point_1_7} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_4_8/design_2_floating_point_4_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_4_8 || ORIG_REF_NAME==design_2_floating_point_4_8} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_5_5/design_2_floating_point_5_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_5_5 || ORIG_REF_NAME==design_2_floating_point_5_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_6_5/design_2_floating_point_6_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_6_5 || ORIG_REF_NAME==design_2_floating_point_6_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_9/design_2_Weight_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_9 || ORIG_REF_NAME==design_2_Weight_0_9} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_1_5/design_2_Weight_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_1_5 || ORIG_REF_NAME==design_2_Weight_1_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_2_5/design_2_Weight_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_2_5 || ORIG_REF_NAME==design_2_Weight_2_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_3_5/design_2_Weight_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_3_5 || ORIG_REF_NAME==design_2_Weight_3_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_register_slice_0_6/design_2_axis_register_slice_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_register_slice_0_6 || ORIG_REF_NAME==design_2_axis_register_slice_0_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_0_6/design_2_Tvalid_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_0_6 || ORIG_REF_NAME==design_2_Tvalid_0_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_1_7/design_2_Tvalid_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_1_7 || ORIG_REF_NAME==design_2_Tvalid_1_7} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_2_5/design_2_Tvalid_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_2_5 || ORIG_REF_NAME==design_2_Tvalid_2_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_3_5/design_2_Tvalid_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_3_5 || ORIG_REF_NAME==design_2_Tvalid_3_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ReLu_0_6/design_2_ReLu_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ReLu_0_6 || ORIG_REF_NAME==design_2_ReLu_0_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_2_6/design_2_floating_point_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_2_6 || ORIG_REF_NAME==design_2_floating_point_2_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_3_6/design_2_floating_point_3_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_3_6 || ORIG_REF_NAME==design_2_floating_point_3_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_10/design_2_floating_point_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_10 || ORIG_REF_NAME==design_2_floating_point_0_10} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_1_8/design_2_floating_point_1_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_1_8 || ORIG_REF_NAME==design_2_floating_point_1_8} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_4_9/design_2_floating_point_4_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_4_9 || ORIG_REF_NAME==design_2_floating_point_4_9} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_5_6/design_2_floating_point_5_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_5_6 || ORIG_REF_NAME==design_2_floating_point_5_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_6_6/design_2_floating_point_6_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_6_6 || ORIG_REF_NAME==design_2_floating_point_6_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_10/design_2_Weight_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_10 || ORIG_REF_NAME==design_2_Weight_0_10} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_1_6/design_2_Weight_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_1_6 || ORIG_REF_NAME==design_2_Weight_1_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_2_6/design_2_Weight_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_2_6 || ORIG_REF_NAME==design_2_Weight_2_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_3_6/design_2_Weight_3_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_3_6 || ORIG_REF_NAME==design_2_Weight_3_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_register_slice_0_7/design_2_axis_register_slice_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_register_slice_0_7 || ORIG_REF_NAME==design_2_axis_register_slice_0_7} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_0_7/design_2_Tvalid_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_0_7 || ORIG_REF_NAME==design_2_Tvalid_0_7} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_1_8/design_2_Tvalid_1_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_1_8 || ORIG_REF_NAME==design_2_Tvalid_1_8} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_2_6/design_2_Tvalid_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_2_6 || ORIG_REF_NAME==design_2_Tvalid_2_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_3_6/design_2_Tvalid_3_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_3_6 || ORIG_REF_NAME==design_2_Tvalid_3_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ReLu_0_7/design_2_ReLu_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ReLu_0_7 || ORIG_REF_NAME==design_2_ReLu_0_7} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_2/design_2_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xbar_2 || ORIG_REF_NAME==design_2_xbar_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_axi_periph_4/design_2_microblaze_0_axi_periph_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_periph_4 || ORIG_REF_NAME==design_2_microblaze_0_axi_periph_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_0_5/design_2_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_5 || ORIG_REF_NAME==design_2_axi_gpio_0_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_0_6/design_2_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_6 || ORIG_REF_NAME==design_2_axi_gpio_0_6} -quiet] -quiet

# IP: bd/design_2/ip/design_2_input_0_0/design_2_input_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_input_0_0 || ORIG_REF_NAME==design_2_input_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_input_0_1/design_2_input_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_input_0_1 || ORIG_REF_NAME==design_2_input_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_input_2_0/design_2_input_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_input_2_0 || ORIG_REF_NAME==design_2_input_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_fifo_mm_s_0_0/design_2_axi_fifo_mm_s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==design_2_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_fifo_mm_s_0_1/design_2_axi_fifo_mm_s_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_fifo_mm_s_0_1 || ORIG_REF_NAME==design_2_axi_fifo_mm_s_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_fifo_mm_s_0_2/design_2_axi_fifo_mm_s_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_fifo_mm_s_0_2 || ORIG_REF_NAME==design_2_axi_fifo_mm_s_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_fifo_mm_s_0_3/design_2_axi_fifo_mm_s_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_fifo_mm_s_0_3 || ORIG_REF_NAME==design_2_axi_fifo_mm_s_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_S_axi_Demultiplexer1_0_0/design_2_S_axi_Demultiplexer1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_S_axi_Demultiplexer1_0_0 || ORIG_REF_NAME==design_2_S_axi_Demultiplexer1_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_S_axi_Demultiplexer1_0_1/design_2_S_axi_Demultiplexer1_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_S_axi_Demultiplexer1_0_1 || ORIG_REF_NAME==design_2_S_axi_Demultiplexer1_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_S_axi_Demultiplexer1_0_2/design_2_S_axi_Demultiplexer1_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_S_axi_Demultiplexer1_0_2 || ORIG_REF_NAME==design_2_S_axi_Demultiplexer1_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_S_axi_Demultiplexer1_0_3/design_2_S_axi_Demultiplexer1_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_S_axi_Demultiplexer1_0_3 || ORIG_REF_NAME==design_2_S_axi_Demultiplexer1_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Seven_Segments_0_0/design_2_Seven_Segments_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Seven_Segments_0_0 || ORIG_REF_NAME==design_2_Seven_Segments_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_2_1/design_2_floating_point_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_2_1 || ORIG_REF_NAME==design_2_floating_point_2_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_3_1/design_2_floating_point_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_3_1 || ORIG_REF_NAME==design_2_floating_point_3_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_0_5/design_2_floating_point_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_5 || ORIG_REF_NAME==design_2_floating_point_0_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_1_3/design_2_floating_point_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_1_3 || ORIG_REF_NAME==design_2_floating_point_1_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_4_4/design_2_floating_point_4_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_4_4 || ORIG_REF_NAME==design_2_floating_point_4_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_5_1/design_2_floating_point_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_5_1 || ORIG_REF_NAME==design_2_floating_point_5_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_floating_point_6_1/design_2_floating_point_6_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_floating_point_6_1 || ORIG_REF_NAME==design_2_floating_point_6_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_0_5/design_2_Weight_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_0_5 || ORIG_REF_NAME==design_2_Weight_0_5} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_1_1/design_2_Weight_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_1_1 || ORIG_REF_NAME==design_2_Weight_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_2_1/design_2_Weight_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_2_1 || ORIG_REF_NAME==design_2_Weight_2_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Weight_3_1/design_2_Weight_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Weight_3_1 || ORIG_REF_NAME==design_2_Weight_3_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axis_register_slice_0_2/design_2_axis_register_slice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axis_register_slice_0_2 || ORIG_REF_NAME==design_2_axis_register_slice_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_0_2/design_2_Tvalid_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_0_2 || ORIG_REF_NAME==design_2_Tvalid_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_1_3/design_2_Tvalid_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_1_3 || ORIG_REF_NAME==design_2_Tvalid_1_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_2_1/design_2_Tvalid_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_2_1 || ORIG_REF_NAME==design_2_Tvalid_2_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Tvalid_3_1/design_2_Tvalid_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_Tvalid_3_1 || ORIG_REF_NAME==design_2_Tvalid_3_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ReLu_0_2/design_2_ReLu_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ReLu_0_2 || ORIG_REF_NAME==design_2_ReLu_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_system_ila_0_1/design_2_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_system_ila_0_1 || ORIG_REF_NAME==design_2_system_ila_0_1} -quiet] -quiet

# XDC: c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/design_2_ooc.xdc
