# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.srcs/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_4/design_2_axis_register_slice_0_4.xci
# IP: The module: 'design_2_axis_register_slice_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_4/design_2_axis_register_slice_0_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_register_slice_0_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_4/design_2_axis_register_slice_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_register_slice_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/4x4NN.srcs/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_4/design_2_axis_register_slice_0_4.xci
# IP: The module: 'design_2_axis_register_slice_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_4/design_2_axis_register_slice_0_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_register_slice_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/giova/Documents/Home/UNI/TESI/1_photontorch/2_fpga/test1/4x4NN/project_1.gen/sources_1/bd/design_2/ip/design_2_axis_register_slice_0_4/design_2_axis_register_slice_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_register_slice_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
